### ISSUE TITLE
DSP.GetParameterInfo throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by LVamos** [sunkin351/FmodAudio#2]
# Bug description

There's a problem with optaining parameter descriptions of a nested DSP plugin. It should contain 13 parameters but I can get descriptions just for parameter 0 to parameter 10. When I access parameter 11 then exception is thrown. I used FMOD 2.0 and Resonance Audio DSP plugin and I was exploring a nested plugin called Source.

# Code causing the exception

```CSharp
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Windows;

using FmodAudio;
using FmodAudio.Dsp;

namespace FmodResonanceExperiment
{
    public static class ResonanceAudio
    {
        public static readonly ReadOnlyDictionary<string, Sound> Sounds;

        private static readonly Dictionary<string, Sound> _sounds;

        private static Plugin _basePlugin;

        private static FmodSystem _fmodSystem;

        private static DSP _listenerDSP;

        private static Plugin _listenerPlugin;

        private static ChannelGroup _masterChannelGroup;

        private static Plugin _nearFieldPlugin;

        private static Plugin _sourcePlugin;

        private static ChannelGroup _spatialChannelGroup;

        static ResonanceAudio()
        {
            _sounds = new Dictionary<string, Sound>();
            Sounds = new ReadOnlyDictionary<string, Sound>(_sounds);
        }/*mtd*/

        public static void AddSound(string fileName, bool loop = false)
        {
            Sound sound = new Sound(fileName, loop, _sourcePlugin, _nearFieldPlugin, _fmodSystem, _spatialChannelGroup);
            _sounds[sound.Name] = sound;
        }

        public static void Free()
            => _fmodSystem.Release();

        public static void Init()
        {
            _fmodSystem = Fmod.CreateSystem();
            _fmodSystem.Init(32);

            _basePlugin = _fmodSystem.LoadPlugin("resonanceaudio.dll");

            _listenerPlugin = _fmodSystem.GetNestedPlugin(_basePlugin, 0);
            _listenerDSP = _fmodSystem.CreateDSPByPlugin(_listenerPlugin);
            _nearFieldPlugin = _fmodSystem.GetNestedPlugin(_basePlugin, 1);
            _sourcePlugin = _fmodSystem.GetNestedPlugin(_basePlugin, 2);

            _masterChannelGroup = _fmodSystem.MasterChannelGroup;
            _spatialChannelGroup = _fmodSystem.CreateChannelGroup("spatial");
            _masterChannelGroup.AddGroup(_spatialChannelGroup, false);

            _spatialChannelGroup.AddDSP(ChannelControlDSPIndex.DSPTail, _listenerDSP);
        }

        public static void ShowPluginsInfo()
        {
            // Local function
            void pluginInfo(DSP plugin)
            {
                Span<char> pluginName = new Span<char>();
                plugin.GetInfo(pluginName, out FmodVersion a, out int b, out int c, out int d);
                string msg = $"Displaying parameters of {new string(pluginName)} plugin.{Environment.NewLine} Parameter count: {plugin.ParameterCount.ToString()}{Environment.NewLine}";

                for (int paramIndex = 0; paramIndex < plugin.ParameterCount; paramIndex++)
                {
                    ParameterDescription description = plugin.GetParameterInfo(paramIndex);
                    msg += $"Parameter index: {paramIndex.ToString() + Environment.NewLine}";
                    msg += $"Name: {description.Name + Environment.NewLine}";
                    msg += $"Short description: {description.Label + Environment.NewLine}";
                }/*for*/

                Clipboard.SetText(msg);

                MessageBox.Show(msg);
            }/*fnc*/

            pluginInfo(_fmodSystem.CreateDSPByPlugin(_sourcePlugin));
        }/*mtd*/

        /*mtd*/
        /*mtd*/
    } /*cls*/
}/*nspc*/
```

**Comment by sunkin351** [comment]
If I may point out, that is not how you use the Span API... It is not like other .NET containers. You must specify where its backing memory is. (e.g. `Span<char> pluginName = new char[256];` or `Span<char> pluginName = stackalloc char[256];`) If you don't, its essentially a null pointer of sorts.

**Comment by sunkin351** [comment]
Could I also get a stack trace please?

**Comment by LVamos** [comment]
Thank you for correction, I'll rewrite the code to use span that way you mentioned. And thanks for your advice with ParameterDescription, now I use an switch expression with is operator.

# Stack trace
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.ReadOnlySpan`1.Slice(Int32 start, Int32 length)
   at FmodAudio.Helpers.MemoryToString(ReadOnlySpan`1 buffer, Encoding encoding)
   at FmodAudio.Helpers.MemoryToString(ReadOnlySpan`1 buffer)
   at FmodAudio.Dsp.ParameterDescription..ctor(ParameterDescriptionStruct* ptr)
   at FmodAudio.Dsp.FloatParameterDescription..ctor(ParameterDescriptionStruct* ptr)
   at FmodAudio.Dsp.ParameterDescription.CreateFromPointer(IntPtr ptr)
   at FmodAudio.Dsp.DSP.GetParameterInfo(Int32 index)
   at FmodResonanceExperiment.ResonanceAudio.<ShowPluginsInfo>g__ShowPluginDetails|14_1(DSP plugin) in C:\Users\Lukáš\OneDrive\škola\bakalářka\programování\příprava na hru\programy na zkoušku\zkoušení zvuku\FmodResonanceExperiment\FmodResonanceExperiment\ResonanceAudio.cs:line 128
   at FmodResonanceExperiment.ResonanceAudio.ShowPluginsInfo() in C:\Users\Lukáš\OneDrive\škola\bakalářka\programování\příprava na hru\programy na zkoušku\zkoušení zvuku\FmodResonanceExperiment\FmodResonanceExperiment\ResonanceAudio.cs:line 137
   at FmodResonanceExperiment.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in C:\Users\Lukáš\OneDrive\škola\bakalářka\programování\příprava na hru\programy na zkoušku\zkoušení zvuku\FmodResonanceExperiment\FmodResonanceExperiment\MainWindow.xaml.cs:line 36
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by sunkin351** [comment]
Didn't see that one coming... `FmodHelpers.MemoryToString()` huh? One moment while I debug that

**Comment by sunkin351** [comment]
Ahh crap... I know what's happening there... You using the nugget package or the repository directly? It won't affect how its fixed but it will affect when you get the fix.

**Comment by LVamos** [comment]
I'm using Nuget but if there's a chance you can fix it quickly I'll use the repository instead.

**Comment by sunkin351** [comment]
Already comited a fix on master, do please try it out.

**Comment by LVamos** [comment]
Yeah, now it works perfectly! Great job! I'm looking forward to future updates.

**Comment by sunkin351** [comment]
Next update will expose a "bare metal" binding to properly support more advanced callbacks and fmod features. I'm working on it as we speak.
